### ISSUE TITLE
Add the prompts in text so that people can cross verify ur models results as u have presented in the image

### ISSUE THREAD

**Issue by Akshay1-6180** [chaoyi-wu/PMC-LLaMA#15]
Prompt 1 : 
Hello, I am a young and healthy teenage girl, but I suffer from many severe UTIs (urinary tract
infections).
I get an average of about eight infections annually over the past four years. I follow all of the
conventional methods of hygiene, including vitamin C intake, using cotton underwear, etc. I drink about a gallon of water daily and exercise. This problem has spread to my kidneys the initial time and has never escalated to that state.
I developed allergies to all antibiotics, so I am unsure how to treat them at this point. Also, I constantly have cloudy urine and lower back pain.
Please help.

Prompt 2:
A microbiologist is studying the emergence of a virulent strain of the virus. After a detailed study of the virus and its life cycle, he proposes a theory: Initially, a host cell is co-infected with 2 viruses from the same virus family. Within the host cell, concomitant production of various genome segments from both viruses occurs. Ultimately, the different genome segments from the viruses are packaged into a unique and novel virus particle. The newly formed virus particle is both stable and viable and is a new strain from the virus family that caused the outbreak of infection. Which of the following viruses is capable of undergoing the above- mentioned process?
A. Epstein-Barr virus
B. Human immunodeficiency virus
C. Rotavirus
D. Vaccinia virus

Prompt 3:
A 26-year-old woman presents to a gynecologist after a missed period. After performing a complete physical examination and a screening test for pregnancy, her gynecologist informs her that she is pregnant. She is very surprised as she has been taking oral contraceptives regularly. When the gynecologist asks her about the consumption of any other medications, she mentions that she was placed on treatment for pulmonary tuberculosis (TB) 2 months ago. Her current anti-TB regimen includes rifampin, isoniazid, pyrazinamide, and ethambutol.
Which of the following mechanisms best explains the failure of oral contraceptives in this patient?
A. Induction of CYP3A4 by rifampin leading to decreased serum levels of ethinylestradiol and progesterone
B. Induction of CYP2A6 by rifampin leading to increased inactivation of ethinylestradiol
C. Interference with the intestinal absorption of the oral contraceptive by pyrazinamide
D. Increased renal elimination of the progesterone component of the oral contraceptive by ethambutol

gave prompt 2 and this is what it gave
<img width="892" alt="Screenshot 2023-09-08 at 1 56 50 PM" src="https://github.com/chaoyi-wu/PMC-LLaMA/assets/65217827/15bf4c70-0d57-4a76-809a-40513976fbf3">
so I looked into it and the 512 prompt length was causing major issues

**Comment by WeixiongLin** [comment]
Hello I have update the input prompt in the demo, so now its behaviour aligns with those described in our paper.
Besides, could you further explain why the 512 prompt length was causing the major issues please. Since the output from assitant seems complete to me.
