### ISSUE TITLE
RecursionError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by pradpalnis** [chaoyi-wu/PMC-LLaMA#18]
logged as "PMC_LLaMA_13B" model & while loading the model got into `RecursionError: maximum recursion depth exceeded
`transformers==4.30.2
[error_trace.txt](https://github.com/chaoyi-wu/PMC-LLaMA/files/12913246/error_trace.txt)

**Comment by qiuhaolu** [comment]
I met the same issue. How did you fix it?
