### ISSUE TITLE
关于预训练

### ISSUE THREAD

**Issue by cocovoc** [chaoyi-wu/PMC-LLaMA#4]
看代码实现 预训练不像往常transformer预训练任务 比如 span mask，  next token prediction 等， 
paperdataset 的label 和input完全一样啊

**Comment by chaoyi-wu** [comment]
Check Line 704-714 in src/transformers/models/llama/modeling_llama.py

**Comment by ZN1010** [comment]
想问一下，这个training objective算是last token prediction吗？看了transformers的代码，貌似每一次只是预测最后一个token，而不是每个token都预测。
谢谢～

**Comment by chaoyi-wu** [comment]
是预测每个token，用的是transformers的实现，每个token都会错位计算loss



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | Nan ***@***.***> |
| 日期 | 2023年08月07日 05:16 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [chaoyi-wu/PMC-LLaMA] 关于预训练 (Issue #4) |

想问一下，这个training objective算是last token prediction吗？看了transformers的代码，貌似每一次只是预测最后一个token，而不是每个token都预测。
谢谢～

**Comment by WeixiongLin** [comment]
如果没有进一步的问题，我暂时关闭这个 issue，有其他需要讨论的我们再打开
